name: Backend CI/CD

env:
  AZURE_WEBAPP_NAME: kardes-aile-backend  # set this to the name of your Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: azure/docker-login@v1
        with:
          login-server: kardesaileregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - run: |
          docker build -f ./Backend/src/KardesAile.AspNetCoreHost/DockerfileAzure -t kardesaileregistry.azurecr.io/kardes-aile-image .
          docker push kardesaileregistry.azurecr.io/kardes-aile-image
          
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'kardes-aile-backend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'kardesaileregistry.azurecr.io/kardes-aile-image'
